language: php

php:
  - 5.6

before_script:
  - composer self-update
  - composer install --prefer-source

notifications:
  slack:
    rooms:
      secure: "d80mD04MZoGrHlW6XTZz83nuJkM+ZCRYKSpU3LPQmQTdScsq7zHUpme5l6PankBWKHVjJePY7UiwACabyJmksPBZ+q0KBnFcmXXAnGx8tfKyUCX3SFaaJYm0Ay+q5tEXswzBydMoXZEh2moRuCE91CXWLZ0SAzhoR976US6VndAunxb4kWTzZLKoVZGxE1QVLrgBC/MJj3IIMCn7umxriKiwrOc7swRwY62kkKOktrKZsqTArImOiGznuliuDIhOZq2wRKBirKWVwVgM+pSIyclgwaFgGUBpSsoJfJuMr8mWXZThanakgDTejhrmLbHkkra8BXSnS18XryHe+G5azt2rzzWvH9mbOk4W42Yfi1iyVLxsfcueU/Erz46UZO7+YOfANYQCCPVELIqruh0ODNNAuedVCkJKlq8ponsuCjJzy5Cg/LYmwN1J6eRRTnsTUYxK7S7fHxjbyoHeN8aVvGCqD0DGLkMe4/Isdn9hfve2vN0W06cX+ivQGoXKvWFnvmr8Xs0l7vJ6kr6HbSjpiJHPVgQI+NHn64Cz5bR5SwQYG6eNSyoY+TmXmYQFllvQWKy+6h8jUeuloSs7Dv1x6S8kv31lBGRaVjLG49XPF8c6pUi/LmlKg+20ebrdjeO0mLDKVAtnidQHIaaHTrRX4gtJQuecC4vxDiMkCGweZyQ="
script:
  - ./vendor/bin/phpunit --coverage-clover ./build/logs/clover.xml
  - ./vendor/bin/phpcs --standard=PSR2 ./src/ ./tests/ -n
  - ./vendor/bin/test-reporter --stdout > codeclimate.json
  - "curl -X POST -d @codeclimate.json -H 'Content-Type: application/json' -H 'User-Agent: Code Climate (PHP Test Reporter v1.0.1-dev)' https://codeclimate.com/test_reports"